Feature antitampering
busenm/cordova-plugin-wkwebview-polyfill pull request #1
Opened 2019-02-25 17:09 UTC by busenm

Se agrega lógica de validación de archivos al flujo de desencriptación de plugin crypt-file a nivel nativo.
Esta lógica consiste en generar un diccionario de hashes de cada archivo al momento de compilar la aplicación, y luego en tiempo de ejecución calcular el hash de cada archivo solicitado y compararlo con el del diccionario.

En caso de no calzar, se asume una modificación maliciosa y la aplicación se detiene y elimina de segundo plano. Además se muestra un mensaje Toast detallando el por qué la aplicación fue cerrada.

2019-02-26 13:42 UTC, smedinamedel requested changes
favor de corregir comentarios

2019-02-26 13:42 UTC, smedinam commented on package.json
> +  "description": "This plugin does nothing at all.",
El mensaje podría describir algo en particular, como optimización o correcciones de código menores dentro de la aplicación, por que con la descripción actual es posible que sea sospechosa para un atacante.

2019-02-26 13:42 UTC, smedinam commented on scripts/helpers/get_plugin_preference.js
> +    return preferences ? preferences[preference] : void 0;
Acá se está preguntando dos veces por "preferences", en el if y en el return posterior, se podría dejar en una sola validación

2019-02-26 13:42 UTC, smedinam commented on src/android/com/tkyaji/cordova/AssetsIntegrity.java
> +        LOG.d(TAG, "checking single file");
Favor de eliminar LOG.d del código

2019-02-26 13:42 UTC, smedinam commented on src/android/com/tkyaji/cordova/DecryptResource.java
> +                LOG.d(TAG, "verifying files");
Favor de eliminar LOG.d del código.

2019-02-26 14:50 UTC, smedinamedel approved these changes

2019-02-26 21:02 UTC, yvera-kunder requested changes
Favor realizar cambios solicitados y realizar pruebas respectivas

2019-02-26 21:02 UTC, yvera-kunder commented on hooks/after_prepare.js
>          if (platform == 'ios') {
Consideración a futuro, en relación a este hook, se recomienda revisar entero, entre otras cosas:
- Cambiar operador de comparación == por  ===
- Ver el manejo de otras _platforms_
- Mejorar nombre de variables
- Ver punto y comas que falten (al final de función forEach por ejemplo);

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/clear_assets_hashes.js
> +#!/usr/bin/env node
Favor mover archivos a hooks, ya que, según lo conversado no es necesario que estén en una carpeta diferente.

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/clear_assets_hashes.js
> +            content = source.content.replace(/\s*put\("[^"]+",\s"[^"]{64}"\);/g, '')
dado que a priori no se sabe que realiza el regex, siempre es recomendable manejarlos como constantes, de tal forma, al invocar la función _replace_, se sabe que contenido se pretende reemplazar.

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/clear_assets_hashes.js
> +            content = source.content.replace(/\s*put\("[^"]+",\s"[^"]{64}"\);/g, '')
Este comentario aplicar para L:16, L:17, L:28

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/clear_assets_hashes.js
> +            content = source.content.replace(/assetsHashes = (@{([^}]*)});/, function (a, b) {
Favor cambiar nombre de variables _a_ y _b_, por nombres más descriptivos.

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/helpers/get_plugin_preference.js
> +        if (Object.keys(preferences).length && typeof preferences[preference] !== 'undefined') {
como recomendación a nivel general, cuando en un if va mas de una condición, es preferible sacarlo a una función que sea descriptiva de la condición

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/helpers/get_plugin_source.js
> +            sourceFile = path.join(platformPath, 'app/src/main/java', filePath);
este path.join, junto  al de L:22, son prácticamente iguales, por ende, mejor sacarlo a una función.

```javascript
        try {
            content = fs.readFileSync(getSourceFilePath('app/src/main/java'), 'utf-8');
        } catch (_e) {
            try {
                content = fs.readFileSync(getSourceFilePath('scr'), 'utf-8');
            } catch (e) {
                helpers.exit('Unable to read java class source at path ' + sourceFile, e);
            }
        }

....
function getSourceFilePath(path) {
    return path.join(platformPath, path, filePath);
}
```

valorar nombre de función

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/save_assets_hashes.js
> +#!/usr/bin/env node
Ver si aplican comentarios ya realizados a este archivo

2019-02-26 21:02 UTC, yvera-kunder commented on scripts/save_assets_hashes.js
> +        list.map(function (file) {
cambiar _.map_ por _.foreach_, o en caso que se quiera mejorar el rendimiento, simplemente ocupar un ciclo _for_

2019-02-26 21:02 UTC, yvera-kunder commented on src/android/com/tkyaji/cordova/AssetsIntegrity.java
> +        byte[] data = new byte[16384];
Tener en consideración sacar valores como constantes

2019-02-28 05:06 UTC, yvera-kunder requested changes
Favor revisar comentario pendiente

2019-02-28 05:06 UTC, yvera-kunder commented on hooks/save_assets_hashes.js
> +            content = content.replace(assetMapRegex, function (a, b) {
Aquí falto aplicar lo mismo para las variables, _a_ y _b_

2019-02-28 13:38 UTC, busenm commented on hooks/save_assets_hashes.js
> +            content = content.replace(assetMapRegex, function (a, b) {
Este segmento de código fue eliminado, ya que la lógica de antitampering solo quedó definida para Android.

2019-02-28 13:39 UTC, busenm commented on src/android/com/tkyaji/cordova/AssetsIntegrity.java
> +        byte[] data = new byte[16384];
Dado que este algoritmo de hash es autocontenido y los valores no son reutilizados en ningún otro lugar, se considera innecesario extraerlos a constantes.

2019-02-28 13:40 UTC, busenm commented on scripts/helpers/get_plugin_source.js
> +            sourceFile = path.join(platformPath, 'app/src/main/java', filePath);
Se llegó a acuerdo y este comentario no será aplicado.

2019-02-28 18:11 UTC, yvera-kunder approved these changes

2019-02-28 20:13 UTC, merged